### ISSUE TITLE
The timeout may not work.

### ISSUE THREAD

**Issue by mushroom080** [Raqbit/mc-pinger#10]
I am using [mc-monitor](https://github.com/itzg/mc-monitor), which depends on this, and the timeout did not work properly.

Use `mcpinger.New` and try to set options as needed, the context will be set.
https://github.com/Raqbit/mc-pinger/blob/d244b7350476572890af86f2ff90e6a938db7210/pinger.go#L175-L187

This will cause it to run without a timeout setting.
https://github.com/Raqbit/mc-pinger/blob/d244b7350476572890af86f2ff90e6a938db7210/pinger.go#L48-L55

This is how mc-monitor is implemented.
https://github.com/itzg/mc-monitor/blob/d54586514b4d3ae9db015c04cf982897eec5aed9/java_status.go#L48-L57

I think it would be better not to set the context here, since it can also be set in `mcpinger.WithContext`, but what do you think?

**Comment by raqbit** [comment]
Yep, that seems to have been an oversight when those options got added.

Fixed with #11, where the `Background` context is only set as a default when no timeout or context option has been set.

**Comment by raqbit** [comment]
Thank you!

Fixed in [v0.2.1](https://github.com/Raqbit/mc-pinger/releases/tag/v0.2.1)

**Comment by mushroom080** [comment]
Thank you for fixing that!
