### ISSUE TITLE
Please create newer tag to include protocol int32 fix

### ISSUE THREAD

**Issue by itzg** [Raqbit/mc-pinger#7]
Please create a newer tag that includes:

https://github.com/Raqbit/mc-pinger/commit/1229469434c0f37d12bf5aa0821f0b89163894f9

This issue https://github.com/itzg/docker-minecraft-server/issues/796 requires this fix.

cc @voruti

**Comment by raqbit** [comment]
Done! https://github.com/Raqbit/mc-pinger/releases/tag/v0.1.1
